---
- name: upgrade
  hosts: all
  remote_user: pi
  become: true
  tasks:
  - name: Update and upgrade apt packages
    yum:
      upgrade: yes
      update_cache: yes
      cache_valid_time: 86400 
